version: '3.9'

services:
  user_microservice:
    container_name: render-manager_microservice
    restart: always
    build: .
    image: render-manager-ms
    ports:
      - "52600:4000"
    networks:
      - red-externa
networks:
  red-externa:
    name: frame_net
    external: true
